### ISSUE TITLE
remove or fix the "VERSION" label inside the images 

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker-inbound-agent#117]
Currently the version tag is defined manually in the metadata.

```
LABEL Description="This is a base image, which allows connecting Jenkins agents via JNLP protocols" Vendor="Jenkins project" Version="3.35-2"
```

It is hard to maintain the tag, and it barely offers any value to tagged images. I suggest either reworking Dockerfile to automatically determine the `Version` tag from the parent image... or to just remove the label entirely

CC @olblak

**Comment by mecm1993** [comment]
I would like to take this issue. @oleg-nenashev

**Comment by oleg-nenashev** [comment]
go for it! 👍

**Comment by mecm1993** [comment]
@oleg-nenashev 

One solution could be to add an `ARG` with the version for the image, in this case, `ARG version=3.35-2`, before the `FROM`. However, it will only work for the first `$version`, and this is due [An ARG declared before a FROM is outside of a build stage](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact).

Therefore, to be able to use the `version` argument, it will require to add another `ARG` instruction without a value. In this case,

```
ARG version=3.35-2
FROM jenkins/slave:$version

ARG version
MAINTAINER Oleg Nenashev <o.v.nenashev@gmail.com>
LABEL Description="This is a base image, which allows connecting Jenkins agents via JNLP protocols" Vendor="Jenkins project" Version="$version"

ARG user=jenkins

USER root
COPY jenkins-agent /usr/local/bin/jenkins-agent
RUN chmod +x /usr/local/bin/jenkins-agent &&\
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave
USER ${user}

ENTRYPOINT ["jenkins-agent"]
``` 

Moreover, with the following solution, the user could be able to specify the `version` dynamically with the `--build-args` flag. For example, the previous image will create the image with the default version **3.35-2**. But, there are newer versions in [Docker Hub](https://hub.docker.com/r/jenkinsci/jnlp-slave/tags), then rather than changing the Dockerfile, the user can run `docker build --build-arg version=3.35-3 -t jnlp .`. 

If you like the idea, I would open a PR with these changes in the Dockerfiles. The other solution, would be to take into consideration your suggestion an remove the LABEL corresponding to the version.

**Comment by oleg-nenashev** [comment]
@mecm1993 The suggestion is definitely better than the current state when the version is just broken in the most of the cases. So I would definitely accept it as an intermediate solution.

Some cons w.r.t the approach:

* https://github.com/jenkinsci/docker-slave and https://github.com/jenkinsci/docker-jnlp-slave have independent versioning, the only overlap is a Remoting version. E.g. now we have `jenkins/slave:3.35-3` and  `jenkins/jnlp-slave:3.35-5`. If we follow the approach, `VERSION` will be actually indicating `jenkins/slave` versions which can deviate from the actual image tag. Still, better than the current state
*I am about enabling Dependabot for this repo. I am not sure the suggested scheme will be handled by Dependabot well. Not a blocker

**Comment by dduportal** [comment]
Fixed by https://github.com/jenkinsci/docker-inbound-agent/pull/122
