### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by darktempla** [jenkinsci/docker-inbound-agent#205]
Currently you support ARM for the Jenkins image but there is no support for the inbound agent.
Can we add this?

https://hub.docker.com/r/jenkins4eval/jenkins/tags

**Comment by MarkEWaite** [comment]
The [upstream reference](https://github.com/jenkinsci/helm-charts/issues/99) suggests adding support for 32 bit ARM images.  I'm opposed to that because I don't believe that we can find people that will provide the long-term support needed for 32 bit ARM images.

The platform SIG is actively working on 64 bit ARM support and has included it on the [Jenkins roadmap](https://www.jenkins.io/project/roadmap/) and as [JENKINS-61775](https://issues.jenkins-ci.org/browse/JENKINS-61775).  The 64 bit ARM images are available from AWS (the Graviton 2 instances).  We have them already available on ci.jenkins.io and are using them to test Docker image building and for a few plugin tests that require multiple platforms.

**Comment by darktempla** [comment]
Hi @MarkEWaite thanks for the prompt reply.

I had hoped since you provide them for Jenkins from a consistency point of view you could support them for this image.

I understand where you are coming from I just personally feel it alienates a lot of people running RaspberryPi clusters and other devices that don't support ARM64 which indirectly hurts Jenkins and it's adoption as if it's too hard to get a Jenkins cluster up and running most will likely go to other CICD platforms as alternatives (eg. drone etc).

If it's a definite NO then we can close this issue?

**Comment by MarkEWaite** [comment]
If your specific request is for Docker support for the Raspberry Pi or other 32 bit ARM platforms, then we can rephrase the title of the issue and close the issue.  I'm not aware of anyone proposing to spend the time and effort to support 32 bit ARM Docker images for Jenkins.  Jenkins agents and Jenkins controllers run on 32 bit ARM when using a Java Virtual Machine that has hotspot just in time compilation (like JDK 8 from Oracle and JDK 11 from AdoptOpenJDK).

Yes, it may alienate users trying to run Jenkins on Raspberry Pi.  While I love my Raspberry Pi configurations (Pi 2, Pi 3, Pi 4, and more), I'm not willing to commit my time to maintain a Docker image for 32 bit Raspberry Pi.

If you would like to become a maintainer, you're welcome to join the [Platform SIG](https://www.jenkins.io/sigs/platform/).  We meet every two weeks to review our progress and discuss next steps.

**Comment by darktempla** [comment]
My request was for an ARM (32-bit) version of the image just as has been authored for Jenkins as highlighted with the link in my initial post. 

Either way @MarkEWaite. I appreciate the time you have put into replying to my post. I appreciate everything in IT is a trade off. Thanks.

**Comment by timja** [comment]
It looks like there is some support for 64 bit in raspberry pi's:
https://www.raspberrypi.org/forums/viewtopic.php?t=275370
