### ISSUE TITLE
Feature Request: Docker-in-Docker support

### ISSUE THREAD

**Issue by HariSekhon** [jenkinsci/docker-inbound-agent#223]
### Feature Request

Please consider adding Docker-in-Docker support.

The TeamCity agent already supports this with a simple enabling of an environment variable and I've used that a lot:

https://hub.docker.com/r/jetbrains/teamcity-agent/

Related issues:

https://github.com/jenkinsci/docker-inbound-agent/issues/215
https://github.com/jenkinsci/docker-inbound-agent/issues/222

**Comment by H1rkul2** [comment]
new pull request opened for this Feature , i used the same technique as teamcity-agent  now you simply need to add the environment variable **DOCKER_IN_DOCKER=start** and mount docker directory in  a volume **docker_volumes:/var/lib/docker** and start it as **--privileged**

`docker run -v docker_volumes:/var/lib/docker --privileged -e DOCKER_IN_DOCKER=start --net jenkins --init jenkins/inbound-agent:dind -url http://jenkins:8080 -workDir=/home/jenkins/agent $SECRET debian`

**Comment by dduportal** [comment]
Update: I'm closing this (rather oldish) issue.

The PR was refused (https://github.com/jenkinsci/docker-inbound-agent/pull/224#issuecomment-906188100) because:

- Docker in Docker in not recommended for security reasons most of the time, unless you have a pretty specific setup with a secured outer container engine.
- The goal of this image is to provide a minimalist Jenkins agent. Docker (even the command line) is not required to execute a standard Jenkins setup. We recommend that you build your own image on top of this one (or using some part of this one using multistage builds) to implement your own Docker CE installation.

As such I'm closing this issue.
