### ISSUE TITLE
Add alpine arm64 docker image builds

### ISSUE THREAD

**Issue by nbr23** [jenkinsci/docker-inbound-agent#395]
### What feature do you want to see added?

Hi!

Could we build the arm64 variant for the alpine based image of the agent?
~I think it might just be a matter of adding alpine to the `linux-arm64` group in docker-bake?~
Looks like we might have a dependency on this first https://github.com/jenkinsci/docker-agent/issues/397

Thanks!

**Comment by dduportal** [comment]
It not possible for now: https://github.com/adoptium/containers/issues/158#issuecomment-1672917735 means that temurin is not available yet, even for JDK21 alpine aarch64.

**Comment by gounthar** [comment]
Temurin is already providing nightly builds of JDK21 for `aarch64/alpine`. However, it's important to note that these builds are nightly builds, which means they are not official stable releases.

Additionally, it's worth mentioning that Jenkins does not currently offer official support for JDK21. So, if we decide to provide a Docker image for it, we would be ahead of the curve compared to the official support status.

That being said, this doesn't necessarily mean we shouldn't provide such an image. It could be a proactive step that allows us to re-integrate Alpine for `aarch64 `as soon as it becomes officially available. 🤔

I know, I know, the next logical step would be for me to propose a PR so that we know if that can be done harmlessly. 🤣

**Comment by dduportal** [comment]
> This all sounds good to me! Happy to help in any capacity I can yes, let me know what I can do!
> 
> Thx!

@nbr23 a first step would be to introduce an initial set of JDK21 "experimental" images on jenkinsci/docker-agent for debian and alpine.

Same idea as the [JDK21 experimental introduction for the controller image](https://github.com/jenkinsci/docker/pull/1683) with the `-preview` tags.


Good news: the addition of a new JDK should be simpler with agent images.

**Comment by dduportal** [comment]
Thanks for https://github.com/jenkinsci/docker-agent/pull/492 @nbr23 !

The release `3148.v532a_7e715ee3-4` is currently being published in the DockerHub: you can start the work on jenkinsci/docker-inbound-agent now.

**Comment by dduportal** [comment]
Aaaand it's implemented and available:

![Capture d’écran 2023-09-08 à 19 21 00](https://github.com/jenkinsci/docker-inbound-agent/assets/1522731/f228317b-9e3e-4377-9f6a-2b1a2cc0463d)


Please note that there are NO guarantuee that Temurin project will keep delivering an alpine `arm64` JDK21 in the future : if they don't, the alpine `arm64` image of the Jenkins agents will be discontinued.


Thanks for the contributions @nbr23 and @gounthar

**Comment by nbr23** [comment]
Sorry, was AFK today, but I see @gounthar was on fire and finished my job and much more! Thanks so much everyone, what an amazing turnaround time!
